---
- name: Copy Generic Application Server Platform Profile Setup file
  template:
    src: gasp-path.sh.j2
    dest: /etc/profile.d/gasp-path.sh
    owner: root
    group: root
    mode: "a+x"

- name: Ensure that the Generic Application Server Platform Directories Exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "u=rwx,g=rwx"
  loop: "{{ gasp_dirs }}"

- name: Install Generic Application Server Platform Scripts
  copy:
    src: platform-bin/
    dest: /gasp-platform/bin
    mode: "u=rwx,g=rwx"

- name: Install Generic Application Server Platform Packages
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ gasp_packages }}"

- name: Ensure that vimrc exists (RedHat Family Distros)
  template:
    src: vimrc.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
    - /etc/vimrc
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: Import NodeSource GPG key
  rpm_key:
    state: present
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL

- name: Install NodeSource repository
  get_url:
    url: https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
    dest: /tmp/nodesource-release-nodistro-1.noarch.rpm

- name: Install the NodeSource repository RPM
  yum:
    name: /tmp/nodesource-release-nodistro-1.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Install Node.js with module hotfixes
  yum:
    name: nodejs
    state: present
    enablerepo: nodesource
    setopt: module_hotfixes=1

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false

- name: Print Node.js version
  debug:
    msg: "Node.js version installed: {{ node_version.stdout }}"

- name: Setup the ansible setup folder
  synchronize:
    src: /tmp/gasp-root/gasp-tools-main/host-setup/
    dest: /gasp-platform/setup
